### PR TITLE
[#61] Protect against parsing empty ranges

### LINKED ISSUE #61: MachObfuscator crashes on empty range in LC_DYLD_INFO_ONLY
`LC_DYLD_INFO_ONLY` can contain empty ranges. MachObfuscator will crash trying to parse an export trie from empty data. MachObfuscator should skip empty ranges.
empty_range

### PR DESCRIPTION
**Pull request by kam800**
Closes #61

### CODE REVIEW

File: MachObfuscator/Mach/Parsing/Mach+classNames.swift [hunk 1]
```diff
@@ -2,7 +2,8 @@ import Foundation
 
 extension Mach {
     var classNames: [String] {
-        guard let classNameSection = objcClassNameSection
+        guard let classNameSection = objcClassNameSection,
```
Comment (kjamroz-bt) [inline MachObfuscator/Mach/Parsing/Mach+classNames.swift]: does it crash when className section is empty?

Comment (kam800) [reply MachObfuscator/Mach/Parsing/Mach+classNames.swift]: To be honest, I only had an issue with empty export trie, but I decided to apply similar fix in all the similar places. In case of `classNames` it looks like the method uses the whole range , not just the `lowerBound` index – so there would be no crash anyway. Let's think about this as early-optimization ;) Do you think I should remove it?

Comment (kjamroz-bt) [reply MachObfuscator/Mach/Parsing/Mach+classNames.swift]: with additional checks code is more consistent, I think they may stay
