### PR TITLE
Handle UTF8 names in realwords mangler

### LINKED ISSUE #24: Handle UTF8 classnames and selectors in RealWordsMangler
In RealWords mangler we need to generate identifier of the same length in bytes as original identifier. Original identifier could contain multibyte UTF8 characters but mangled names contain only ascii characters.

Currently MachObfuscator crashes on precondition in Data.replaceStrings due to different lengths in bytes before and after mangling.

### PR DESCRIPTION
**Pull request by kjamroz-bt**
Closes #24.
This PR adds some debug logs, so it requires that #23 is merged first.

### CODE REVIEW

File: MachObfuscator/Controller/Obfuscator.swift [hunk 1]
```diff
@@ -30,6 +30,17 @@ class Obfuscator {
         LOGGER.info("\(symbols.blacklist.classes.count) unobfuscable classes")
 
         LOGGER.info("Mangling symbols...")
+        symbols.whitelist.selectors.filter {
+            $0.utf8.count != $0.count
```
Comment (kam800) [inline MachObfuscator/Controller/Obfuscator.swift]: I don't think leaving those changes here is a good idea. I imagine they were helpful during development, but they add little value on production. Additionally those computations are going to be executed every time (even when log level is non-debug). Would you mind removing those changes? I am going to add obfuscation reports, so I think this will become a little redundant.

Alternatively, if you really think those changes can be helpful in the future, would you mind improving them a little bit by applying following changes?:
1) checking for a debug log level before executing those changes?
2) extracting those changes to `ObfuscationSymbols` extension?
3) extracting `$0.utf8.count != $0.count` as `String.containsAsciiCharacters`?

File: MachObfuscator/SymbolMangling/RealWordsMangler/RealWordsMangler.swift [hunk 2]
```diff
@@ -70,7 +70,7 @@ private extension ObfuscationSymbols {
     func classManglingMap(sentenceGenerator: SentenceGenerator) -> [(String, String)] {
         let mangledClassesBlacklist = (Array(blacklist.classes) + Array(whitelist.classes)).uniq
         let classManglingEntryProvider: (String) -> (String, String)? = { className in
-            while let randomClassName = sentenceGenerator.getUniqueSentence(length: className.count)?.capitalizedOnFirstLetter {
+            while let randomClassName = sentenceGenerator.getUniqueSentence(length: className.utf8.count)?.capitalizedOnFirstLetter {
```
Comment (kam800) [inline MachObfuscator/SymbolMangling/RealWordsMangler/RealWordsMangler.swift]: Could you please add some unit tests for those changes?

File: MachObfuscator/Controller/Obfuscator.swift (hunk 1 above)
Comment (kjamroz-bt) [reply MachObfuscator/Controller/Obfuscator.swift]: These logs were added out of curiosity. I agree, that a comprehensive reporting will be much better for obtaining such data. I will remove the logs.

File: MachObfuscator/SymbolMangling/RealWordsMangler/RealWordsMangler.swift (hunk 2 above)
Comment (kjamroz-bt) [reply MachObfuscator/SymbolMangling/RealWordsMangler/RealWordsMangler.swift]: tests added

**Comment by kam800** [comment]
Thanks for those changes!
